use kanden_generated::{block::BlockState, particles::*};
use kanden_math::{DVec3, Vec3};

use crate::{BlockPos, Decode, Encode, ItemStack, Packet, VarInt};

#[derive(Clone, Debug, Packet, Encode, Decode)]
pub struct LevelParticlesS2c {
    pub long_distance: bool,
    pub always_visible: bool,
    pub position: DVec3,
    pub offset: Vec3,
    pub max_speed: f32,
    pub count: i32,
    pub particle: Particle,
}

#[derive(Clone, PartialEq, Debug, Encode, Decode)]
pub enum Particle {
    AngryVillager,
    Block(BlockState),
    BlockMarker(BlockState),
    Bubble,
    Cloud,
    CopperFireFlame,
    Crit,
    DamageIndicator,
    DragonBreath {
        power: f32,
    },
    DrippingLava,
    FallingLava,
    LandingLava,
    DrippingWater,
    FallingWater,
    Dust {
        /// The color, encoded as 0xRRGGBB; top bits are ignored.
        /// TODO: Does kanden have a type for this?
        color: i32,
        //// The scale, will be clamped between 0.01 and 4.
        scale: f32,
    },
    DustColorTransition {
        /// The color to transition from, encoded as 0xRRGGBB; top bits are
        /// ignored. TODO: Does kanden have a type for this?
        from_color: i32,
        /// The color to transition from, encoded as 0xRRGGBB; top bits are
        /// ignored. TODO: Does kanden have a type for this?
        to_color: i32,
        /// The scale, will be clamped between 0.01 and 4.
        scale: f32,
    },
    Effect {
        color: i32,
        power: f32,
    },
    ElderGuardian,
    EnchantedHit,
    Enchant,
    EndRod,
    EntityEffect {
        /// The ARGB components of the color encoded as an Int
        /// TODO: proper type
        color: i32,
    },
    ExplosionEmitter,
    Explosion,
    Gust,
    SmallGust,
    GustEmitterLarge,
    GustEmitterSmall,
    SonicBoom,
    FallingDust(BlockState),
    Firework,
    Fishing,
    Flame,
    Infested,
    CherryLeaves,
    PaleOakLeaves,
    TintedLeaves {
        /// The ARGB components of the color encoded as an Int
        /// TODO: type
        color: i32,
    },
    SculkSoul,
    SculkCharge {
        /// How much the particle will be rotated when displayed.
        roll: f32,
    },
    SculkChargePop,
    SoulFireFlame,
    Soul,
    Flash {
        color: i32,
    },
    HappyVillager,
    Composter,
    Heart,
    InstantEffect {
        color: i32,
        power: f32,
    },
    /// If the item is air or its count is 0, the client might crash.
    // TODO: add check when encoding maybe?
    Item(Box<ItemStack>),
    Vibration {
        /// The type of the vibration source defined by the
        /// `minecraft:position_source_type` builtin registry.
        source: VibrationSourceType,
        /// The amount of ticks it takes for the vibration to travel from its
        /// source to its destination.
        ticks: VarInt,
    },
    Trail {
        position: DVec3,
        /// The trail color, encoded as 0xRRGGBB; top bits are ignored.
        color: i32,
        /// Life time in ticks
        duration: VarInt,
    },
    ItemSlime,
    ItemCobweb,
    ItemSnowball,
    LargeSmoke,
    Lava,
    Mycelium,
    Note,
    Poof,
    Portal,
    Rain,
    Smoke,
    WhiteSmoke,
    Sneeze,
    Spit,
    SquidInk,
    SweepAttack,
    TotemOfUndying,
    Underwater,
    Splash,
    Witch,
    BubblePop,
    CurrentDown,
    BubbleColumnUp,
    Nautilus,
    Dolphin,
    CampfireCosySmoke,
    CampfireSignalSmoke,
    DrippingHoney,
    FallingHoney,
    LandingHoney,
    FallingNectar,
    FallingSporeBlossom,
    Ash,
    CrimsonSpore,
    WarpedSpore,
    SporeBlossomAir,
    DrippingObsidianTear,
    FallingObsidianTear,
    LandingObsidianTear,
    ReversePortal,
    WhiteAsh,
    SmallFlame,
    Snowflake,
    DrippingDripstoneLava,
    FallingDripstoneLava,
    DrippingDripstoneWater,
    FallingDripstoneWater,
    GlowSquidInk,
    Glow,
    WaxOn,
    WaxOff,
    ElectricSpark,
    Scrape,
    Shriek {
        /// The time in ticks before the particle is displayed
        delay: VarInt,
    },
    EggCrack,
    DustPlume,
    TrialSpawnerDetection,
    TrialSpawnerDetectionOminous,
    VaultConnection,
    DustPillar(BlockState),
    OminousSpawning,
    RaidOmen,
    TrialOmen,
    BlockCrumble(BlockState),
    Firefly,
}

#[derive(Clone, PartialEq, Debug, Encode, Decode)]
pub enum VibrationSourceType {
    Block {
        /// The position of the block the vibration originated from.
        block_pos: BlockPos,
    },
    Entity {
        /// The ID of the entity the vibration originated from.
        // Based on the context im assuming this is not a EntityKind but a reference to a living
        // entity, do we have access to this from kanden?
        kind: VarInt,
        /// Entity eye height.
        eye_height: f32,
    },
}

impl Particle {
    pub const fn id(&self) -> i32 {
        match self {
            Particle::AngryVillager => ID_ANGRY_VILLAGER,
            Particle::Block(_) => ID_BLOCK,
            Particle::BlockMarker(_) => ID_BLOCK_MARKER,
            Particle::Bubble => ID_BUBBLE,
            Particle::Cloud => ID_CLOUD,
            Particle::CopperFireFlame => ID_COPPER_FIRE_FLAME,
            Particle::Crit => ID_CRIT,
            Particle::DamageIndicator => ID_DAMAGE_INDICATOR,
            Particle::DragonBreath { .. } => ID_DRAGON_BREATH,
            Particle::DrippingLava => ID_DRIPPING_LAVA,
            Particle::FallingLava => ID_FALLING_LAVA,
            Particle::LandingLava => ID_LANDING_LAVA,
            Particle::DrippingWater => ID_DRIPPING_WATER,
            Particle::FallingWater => ID_FALLING_WATER,
            Particle::Dust { .. } => ID_DUST,
            Particle::DustColorTransition { .. } => ID_DUST_COLOR_TRANSITION,
            Particle::Effect { .. } => ID_EFFECT,
            Particle::ElderGuardian => ID_ELDER_GUARDIAN,
            Particle::EnchantedHit => ID_ENCHANTED_HIT,
            Particle::Enchant => ID_ENCHANT,
            Particle::EndRod => ID_END_ROD,
            Particle::EntityEffect { .. } => ID_ENTITY_EFFECT,
            Particle::ExplosionEmitter => ID_EXPLOSION_EMITTER,
            Particle::Explosion => ID_EXPLOSION,
            Particle::Gust => ID_GUST,
            Particle::SmallGust => ID_SMALL_GUST,
            Particle::GustEmitterLarge => ID_GUST_EMITTER_LARGE,
            Particle::GustEmitterSmall => ID_GUST_EMITTER_SMALL,
            Particle::SonicBoom => ID_SONIC_BOOM,
            Particle::FallingDust(_) => ID_FALLING_DUST,
            Particle::Firework => ID_FIREWORK,
            Particle::Fishing => ID_FISHING,
            Particle::Flame => ID_FLAME,
            Particle::Infested => ID_INFESTED,
            Particle::CherryLeaves => ID_CHERRY_LEAVES,
            Particle::PaleOakLeaves => ID_PALE_OAK_LEAVES,
            Particle::TintedLeaves { .. } => ID_TINTED_LEAVES,
            Particle::SculkSoul => ID_SCULK_SOUL,
            Particle::SculkCharge { .. } => ID_SCULK_CHARGE,
            Particle::SculkChargePop => ID_SCULK_CHARGE_POP,
            Particle::SoulFireFlame => ID_SOUL_FIRE_FLAME,
            Particle::Soul => ID_SOUL,
            Particle::Flash { .. } => ID_FLASH,
            Particle::HappyVillager => ID_HAPPY_VILLAGER,
            Particle::Composter => ID_COMPOSTER,
            Particle::Heart => ID_HEART,
            Particle::InstantEffect { .. } => ID_INSTANT_EFFECT,
            Particle::Item(..) => ID_ITEM,
            Particle::Vibration { .. } => ID_VIBRATION,
            Particle::Trail { .. } => ID_TRAIL,
            Particle::ItemSlime => ID_ITEM_SLIME,
            Particle::ItemCobweb => ID_ITEM_COBWEB,
            Particle::ItemSnowball => ID_ITEM_SNOWBALL,
            Particle::LargeSmoke => ID_LARGE_SMOKE,
            Particle::Lava => ID_LAVA,
            Particle::Mycelium => ID_MYCELIUM,
            Particle::Note => ID_NOTE,
            Particle::Poof => ID_POOF,
            Particle::Portal => ID_PORTAL,
            Particle::Rain => ID_RAIN,
            Particle::Smoke => ID_SMOKE,
            Particle::WhiteSmoke => ID_WHITE_SMOKE,
            Particle::Sneeze => ID_SNEEZE,
            Particle::Spit => ID_SPIT,
            Particle::SquidInk => ID_SQUID_INK,
            Particle::SweepAttack => ID_SWEEP_ATTACK,
            Particle::TotemOfUndying => ID_TOTEM_OF_UNDYING,
            Particle::Underwater => ID_UNDERWATER,
            Particle::Splash => ID_SPLASH,
            Particle::Witch => ID_WITCH,
            Particle::BubblePop => ID_BUBBLE_POP,
            Particle::CurrentDown => ID_CURRENT_DOWN,
            Particle::BubbleColumnUp => ID_BUBBLE_COLUMN_UP,
            Particle::Nautilus => ID_NAUTILUS,
            Particle::Dolphin => ID_DOLPHIN,
            Particle::CampfireCosySmoke => ID_CAMPFIRE_COSY_SMOKE,
            Particle::CampfireSignalSmoke => ID_CAMPFIRE_SIGNAL_SMOKE,
            Particle::DrippingHoney => ID_DRIPPING_HONEY,
            Particle::FallingHoney => ID_FALLING_HONEY,
            Particle::LandingHoney => ID_LANDING_HONEY,
            Particle::FallingNectar => ID_FALLING_NECTAR,
            Particle::FallingSporeBlossom => ID_FALLING_SPORE_BLOSSOM,
            Particle::Ash => ID_ASH,
            Particle::CrimsonSpore => ID_CRIMSON_SPORE,
            Particle::WarpedSpore => ID_WARPED_SPORE,
            Particle::SporeBlossomAir => ID_SPORE_BLOSSOM_AIR,
            Particle::DrippingObsidianTear => ID_DRIPPING_OBSIDIAN_TEAR,
            Particle::FallingObsidianTear => ID_FALLING_OBSIDIAN_TEAR,
            Particle::LandingObsidianTear => ID_LANDING_OBSIDIAN_TEAR,
            Particle::ReversePortal => ID_REVERSE_PORTAL,
            Particle::WhiteAsh => ID_WHITE_ASH,
            Particle::SmallFlame => ID_SMALL_FLAME,
            Particle::Snowflake => ID_SNOWFLAKE,
            Particle::DrippingDripstoneLava => ID_DRIPPING_DRIPSTONE_LAVA,
            Particle::FallingDripstoneLava => ID_FALLING_DRIPSTONE_LAVA,
            Particle::DrippingDripstoneWater => ID_DRIPPING_DRIPSTONE_WATER,
            Particle::FallingDripstoneWater => ID_FALLING_DRIPSTONE_WATER,
            Particle::GlowSquidInk => ID_GLOW_SQUID_INK,
            Particle::Glow => ID_GLOW,
            Particle::WaxOn => ID_WAX_ON,
            Particle::WaxOff => ID_WAX_OFF,
            Particle::ElectricSpark => ID_ELECTRIC_SPARK,
            Particle::Scrape => ID_SCRAPE,
            Particle::Shriek { .. } => ID_SHRIEK,
            Particle::EggCrack => ID_EGG_CRACK,
            Particle::DustPlume => ID_DUST_PLUME,
            Particle::TrialSpawnerDetection => ID_TRIAL_SPAWNER_DETECTION,
            Particle::TrialSpawnerDetectionOminous => ID_TRIAL_SPAWNER_DETECTION_OMINOUS,
            Particle::VaultConnection => ID_VAULT_CONNECTION,
            Particle::DustPillar(_) => ID_DUST_PILLAR,
            Particle::OminousSpawning => ID_OMINOUS_SPAWNING,
            Particle::RaidOmen => ID_RAID_OMEN,
            Particle::TrialOmen => ID_TRIAL_OMEN,
            Particle::BlockCrumble(_) => ID_BLOCK_CRUMBLE,
            Particle::Firefly => ID_FIREFLY,
        }
    }
}
